name: GCP Setup and Deployment

on:
  push:
    branches:
      - main
      - '*'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  DOCKER_REPOSITORY_LOCATION: europe-west1
  DOCKER_REPOSITORY_URL: ${{ secrets.GCP_DOCKER_REPO_URL }}
  IMAGE_NAME: "cookeo-a-retro"
  SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
  WIP_POOL: ${{ secrets.GCP_WIP_POOL }}



jobs:
  gcp-setup:
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
    
      - name: Docker login
        id: docker-auth
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: 'oauth2accesstoken'
          password: ${{ steps.auth.outputs.access_token }}



  build-and-deploy:
    runs-on: ubuntu-latest
    needs: gcp-setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/docker/cookeo-a-retro${{ github.ref == 'refs/heads/main' && '' || format('-{0}', github.ref_name) }} .

      - name: Push Docker Image to Artifact Registry
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/docker/cookeo-a-retro${{ github.ref == 'refs/heads/main' && '' || format('-{0}', github.ref_name) }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/docker/cookeo-a-retro${{ github.ref == 'refs/heads/main' && '' || format('-{0}', github.ref_name) }}
          tag: latest
          region: europe-west1  # Replace with your desired region
          platform: managed
          timeout: 120  # Optional: Set a timeout for the deployment

  gcp-cleanup:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'deleted' && github.ref_type == 'branch' && !contains(github.ref, 'main') }}
    steps:
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Delete Docker Image from Artifact Registry
        run: |
          docker login -u _token -p ${{ secrets.GCP_SA_KEY }} gcr.io
          docker pull gcr.io/${{ secrets.GCP_PROJECT_ID }}/cookeo-a-retro${{ github.ref_name }}
          docker rmi gcr.io/${{ secrets.GCP_PROJECT_ID }}/cookeo-a-retro${{ github.ref_name }}
